{"pub": "zdnet", "url": "https://www.zdnet.fr/actualites/avast-une-nouvelle-attaque-a-vise-son-reseau-vpn-interne-39892555.htm", "downloaded_at": "2019-10-22 13:29:29.635013+00:00", "title": "Avast : une nouvelle attaque a vis\u00e9 son r\u00e9seau VPN interne", "language": "fr", "error": "not english"}